#!/usr/bin/env python3
"""Probe Greenhouse board slugs for valid public APIs."""

from __future__ import annotations

import json
import sys
import urllib.error
import urllib.request
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from config import GREENHOUSE_BOARDS

CANDIDATES = {
    # Neuro / brain / biosignals (Beacon-like)
    "beaconbiosignals": "Beacon Biosignals",
    "motifneuro": "Motif Neurotech",
    "motifneurotech": "Motif Neurotech",
    "motif": "Motif Neurotech",
    "neuroelectrics": "Neuroelectrics",
    "neuropace": "NeuroPace",
    "neuroelectricsusa": "Neuroelectrics",
    "brainscope": "BrainScope",
    "braincheck": "BrainCheck",
    "neurotrack": "Neurotrack",
    "neuroflow": "NeuroFlow",
    "neuroxess": "NeuroXess",
    "neurotech": "Neurotech",
    "neuralink": "Neuralink",
    "paradromics": "Paradromics",
    "synchron": "Synchron",
    "blackrockneurotech": "Blackrock Neurotech",
    "precisionneuroscience": "Precision Neuroscience",
    "neuralace": "Neuralace",
    "flowneuroscience": "Flow Neuroscience",
    "neuronetics": "Neuronetics",
    "neurocrine": "Neurocrine Biosciences",
    "cerevel": "Cerevel Therapeutics",
    "cereveltherapeutics": "Cerevel Therapeutics",
    "acadia": "Acadia Pharmaceuticals",
    "sage": "Sage Therapeutics",
    "sagetherapeutics": "Sage Therapeutics",
    "karuna": "Karuna Therapeutics",
    "compasspathways": "Compass Pathways",
    "atai": "atai Life Sciences",
    "mindmed": "MindMed",
    "cybin": "Cybin",
    "ghresearch": "GH Research",
    "fieldtriphealth": "Field Trip Health",
    "mindbloom": "Mindbloom",
    "bighealth": "Big Health",
    "peartherapeutics": "Pear Therapeutics",
    "akiliinteractive": "Akili Interactive",
    "akili": "Akili Interactive",
    "clicktherapeutics": "Click Therapeutics",
    "happifyhealth": "Happify Health",
    "happify": "Happify Health",
    "mindstrong": "Mindstrong",
    "woebothealth": "Woebot Health",
    "woebot": "Woebot Health",
    "springhealth66": "Spring Health",
    "springhealth": "Spring Health",
    "octave": "Octave",
    "twochairs": "Two Chairs",
    "growtherapy": "Grow Therapy",
    "talkiatry": "Talkiatry",
    "donefirst": "Done",
    "done": "Done",
    "equiphealth": "Equip",
    "equip": "Equip",
    "charliehealth": "Charlie Health",
    "charlie": "Charlie Health",
    "withinhealth": "Within Health",
    "within": "Within Health",
    # Digital health / clinical data / diagnostics
    "tempus": "Tempus",
    "flatiron": "Flatiron Health",
    "guardanthealth": "Guardant Health",
    "guardant": "Guardant Health",
    "exactsciences": "Exact Sciences",
    "grail": "GRAIL",
    "invitae": "Invitae",
    "myriad": "Myriad Genetics",
    "genedx": "GeneDx",
    "color": "Color Health",
    "colorhealth": "Color Health",
    "neogenomics": "NeoGenomics",
    "foundationmedicine": "Foundation Medicine",
    "foundation": "Foundation Medicine",
    "caris": "Caris Life Sciences",
    "personalis": "Personalis",
    "adaptivebiotechnologies": "Adaptive Biotechnologies",
    "adaptive": "Adaptive Biotechnologies",
    "thirdeye": "Third Eye Diagnostics",
    "proscia": "Proscia",
    "paige": "Paige",
    "pathai": "PathAI",
    "tempuslabs": "Tempus",
    "somalogic": "SomaLogic",
    "natera": "Natera",
    "illumina": "Illumina",
    "pacbio": "PacBio",
    "nanostring": "NanoString",
    "10x": "10x Genomics",
    "singularity": "Singular Genomics",
    "ultimagenomics": "Ultima Genomics",
    "element": "Element Biosciences",
    "benchling": "Benchling",
    "ginkgo": "Ginkgo Bioworks",
    "insitro": "Insitro",
    "recursion": "Recursion",
    "owkin": "Owkin",
    "benevolent": "BenevolentAI",
    "exscientia": "Exscientia",
    "schrodinger": "Schrodinger",
    "relay": "Relay Therapeutics",
    "beam": "Beam Therapeutics",
    "editas": "Editas Medicine",
    "intellia": "Intellia Therapeutics",
    "crispr": "CRISPR Therapeutics",
    "sana": "Sana Biotechnology",
    "moderna": "Moderna",
    "biontech": "BioNTech",
    "alnylam": "Alnylam Pharmaceuticals",
    "bluebirdbio": "bluebird bio",
    "bluebird": "bluebird bio",
    "vertex": "Vertex Pharmaceuticals",
    "regeneron": "Regeneron",
    "biogen": "Biogen",
    "amgen": "Amgen",
    "gilead": "Gilead Sciences",
    "veeva": "Veeva",
    "medidata": "Medidata",
    "iqvia": "IQVIA",
    "medpace": "Medpace",
    "parexel": "Parexel",
    "syneos": "Syneos Health",
    "icon": "ICON",
    "labcorp": "Labcorp",
    "quest": "Quest Diagnostics",
    # Medtech / devices / remote monitoring
    "dexcom": "Dexcom",
    "insulet": "Insulet",
    "tandemdiabetes": "Tandem Diabetes",
    "tandem": "Tandem Diabetes",
    "livongo": "Livongo",
    "livongohealth": "Livongo",
    "ihealthlabs": "iHealth Labs",
    "withings": "Withings",
    "whoop": "WHOOP",
    "ouraring": "Oura",
    "oura": "Oura",
    "levels": "Levels",
    "functionhealth": "Function Health",
    "function": "Function Health",
    "insideTracker": "InsideTracker",
    "insidetracker": "InsideTracker",
    "heartflow": "HeartFlow",
    "heartflowinc": "HeartFlow",
    "viz": "Viz.ai",
    "vizai": "Viz.ai",
    "aidoc": "Aidoc",
    "zebra-med": "Zebra Medical",
    "zebra": "Zebra Medical",
    "qventus": "Qventus",
    "butterflynetwork": "Butterfly Network",
    "butterfly": "Butterfly Network",
    "hologic": "Hologic",
    "bd": "BD",
    "bectondickinson": "BD",
    "medtronic": "Medtronic",
    "abbott": "Abbott",
    "bostonscientific": "Boston Scientific",
    "stryker": "Stryker",
    "zimmerbiomet": "Zimmer Biomet",
    "edwards": "Edwards Lifesciences",
    "intuitive": "Intuitive Surgical",
    "biofourmis": "Biofourmis",
    "currenthealth": "Current Health",
    "current": "Current Health",
    "spacelabs": "Spacelabs Healthcare",
    "philips": "Philips",
    "gehealthcare": "GE HealthCare",
    "siemenshealthineers": "Siemens Healthineers",
    "siemens": "Siemens Healthineers",
    # Care delivery / virtual care
    "teladoc": "Teladoc",
    "amwell": "Amwell",
    "mdlive": "MDLive",
    "98point6": "98point6",
    "includedhealth": "Included Health",
    "grandrounds": "Included Health",
    "accolade": "Accolade",
    "quantumhealth": "Quantum Health",
    "devoted": "Devoted Health",
    "devotedhealth": "Devoted Health",
    "alignmenthealthcare": "Alignment Healthcare",
    "alignment": "Alignment Healthcare",
    "agilonhealth": "Agilon Health",
    "agilon": "Agilon Health",
    "signifyhealth": "Signify Health",
    "signify": "Signify Health",
    "somatus": "Somatus",
    "cityblock": "Cityblock Health",
    "oakstreethealth": "Oak Street Health",
    "oakstreet": "Oak Street Health",
    "canopy": "Canopy",
    "fireflyhealth": "Firefly Health",
    "firefly": "Firefly Health",
    "hatch": "Hatch",
    "alto": "Alto Pharmacy",
    "altopharmacy": "Alto Pharmacy",
    "capsule": "Capsule",
    "pillpack": "PillPack",
    "goodrx": "GoodRx",
    "hims": "Hims & Hers",
    "forhims": "Hims & Hers",
    "ro": "Ro",
    "nurx": "Nurx",
    "keeps": "Keeps",
    "curology": "Curology",
    "everlywell": "Everlywell",
    "letsgetchecked": "LetsGetChecked",
    "imaware": "Imaware",
    "nourish": "Nourish",
    "seasonhealth": "Season Health",
    "season": "Season Health",
    "virta": "Virta Health",
    "virtahealth": "Virta Health",
    "omada": "Omada Health",
    "omadahealth": "Omada Health",
    "noom": "Noom",
    "calibrate": "Calibrate",
    "foundhealth": "Found",
    "found": "Found",
    "plume": "Plume",
    "folx": "Folx Health",
    "folxhealth": "Folx Health",
    "tia": "Tia",
    "parsley": "Parsley Health",
    "parsleyhealth": "Parsley Health",
    "oneMedical": "One Medical",
    "onemedical": "One Medical",
    "amazononemedical": "One Medical",
    "forward": "Forward",
    "forwardhealth": "Forward",
    "crossoverhealth": "Crossover Health",
    "crossover": "Crossover Health",
    "wheel": "Wheel",
    "wheelhealth": "Wheel",
    "nabla": "Nabla",
    "suki": "Suki",
    "augmedix": "Augmedix",
    "notable": "Notable Health",
    "abridge": "Abridge",
    "sully": "Sully.ai",
    "freed": "Freed",
    "deepScribe": "DeepScribe",
    "deepscribe": "DeepScribe",
    "ambiencehealthcare": "Ambience Healthcare",
    "ambience": "Ambience Healthcare",
    "athelas": "Athelas",
    "athelashealth": "Athelas",
    "healthgorilla": "Health Gorilla",
    "particlehealth": "Particle Health",
    "particle": "Particle Health",
    "redoxengine": "Redox",
    "redox": "Redox",
    "healthcatalyst": "Health Catalyst",
    "innovaccer": "Innovaccer",
    "smiledigitalhealth": "Smile Digital Health",
    "smilecdr": "Smile Digital Health",
    "flexpa": "Flexpa",
    "metriport": "Metriport",
    "zushealth": "Zus Health",
    "zus": "Zus Health",
    "bamboohealth": "Bamboo Health",
    "bamboo": "Bamboo Health",
    "healthie": "Healthie",
    "ribbonhealth": "Ribbon Health",
    "ribbon": "Ribbon Health",
    "turquoisehealth": "Turquoise Health",
    "turquoise": "Turquoise Health",
    "h1": "H1",
    "komodohealth": "Komodo Health",
    "komodo": "Komodo Health",
    "truveta": "Truveta",
    "datavant": "Datavant",
    "nomihealth": "Nomi Health",
    "nomi": "Nomi Health",
    "sidecarhealth": "Sidecar Health",
    "sidecar": "Sidecar Health",
    "rightwayhealthcare": "Rightway Healthcare",
    "rightway": "Rightway Healthcare",
    "strivehealth": "Strive Health",
    "strive": "Strive Health",
    "courierhealth": "Courier Health",
    "courier": "Courier Health",
    "waymark": "Waymark",
    "pomelocare": "Pomelo Care",
    "pomelo": "Pomelo Care",
    "khealth": "K Health",
    "khealthcareers": "K Health",
    "healthverity": "HealthVerity",
    "collectivehealth": "Collective Health",
    "collective": "Collective Health",
    "cloverhealth": "Clover Health",
    "clover": "Clover Health",
    "oscar": "Oscar Health",
    "brighthealth": "Bright Health",
    "bright": "Bright Health",
    "candidhealth": "Candid Health",
    "candid": "Candid Health",
    "curative": "Curative",
    "honor": "Honor",
    "hazel": "Hazel Health",
    "hazelhealth": "Hazel Health",
    "carbon": "Carbon Health",
    "carbonhealth": "Carbon Health",
    "village": "VillageMD",
    "villagemd": "VillageMD",
    "patientpoint": "PatientPoint",
    "florencehealthcare": "Florence Healthcare",
    "florence": "Florence Healthcare",
    "medable": "Medable",
    "science37": "Science 37",
    "science37inc": "Science 37",
    "threadresearch": "Thread Research",
    "thread": "Thread Research",
    "verily": "Verily",
    "verilylife": "Verily",
    "23andme": "23andMe",
    "ancestry": "Ancestry",
    "nebula": "Nebula Genomics",
    "helix": "Helix",
    "sequencing": "Sequencing.com",
    "synthego": "Synthego",
    "mammothbiosciences": "Mammoth Biosciences",
    "mammoth": "Mammoth Biosciences",
    "arborbiotechnologies": "Arbor Biotechnologies",
    "arbor": "Arbor Biotechnologies",
    "inscripta": "Inscripta",
    "scalebio": "Scale Biosciences",
    "parsebiosciences": "Parse Biosciences",
    "parse": "Parse Biosciences",
    "dovetailgenomics": "Dovetail Genomics",
    "dovetail": "Dovetail Genomics",
    "bionano": "Bionano Genomics",
    "oxfordnanopore": "Oxford Nanopore",
    "nanopore": "Oxford Nanopore",
    "twist": "Twist Bioscience",
    "twistbioscience": "Twist Bioscience",
    "freenome": "Freenome",
    "billiontoone": "BillionToOne",
    "veracyte": "Veracyte",
    "tessera": "Tessera Therapeutics",
    "tesseratherapeutics": "Tessera Therapeutics",
    "generate": "Generate Biomedicines",
    "generatebiomedicines": "Generate Biomedicines",
    "elementbiosciences": "Element Biosciences",
    "beamtherapeutics": "Beam Therapeutics",
    "relaytherapeutics": "Relay Therapeutics",
    "proscia": "Proscia",
    "pathai": "PathAI",
    "ginkgobioworks": "Ginkgo Bioworks",
    "recursionpharmaceuticals": "Recursion",
}


def probe(slug: str) -> tuple[bool, int, str]:
    url = f"https://boards-api.greenhouse.io/v1/boards/{slug}/jobs"
    request = urllib.request.Request(
        url,
        headers={"Accept": "application/json", "User-Agent": "job-search-agent/1.0"},
    )
    try:
        with urllib.request.urlopen(request, timeout=10) as response:
            payload = json.load(response)
        jobs = payload.get("jobs", [])
        company = payload.get("meta", {}).get("company_name") or slug
        return True, len(jobs), company
    except urllib.error.HTTPError as exc:
        return False, exc.code, slug
    except urllib.error.URLError:
        return False, -1, slug


def main() -> None:
    existing = set(GREENHOUSE_BOARDS.keys())
    new_valid: list[tuple[str, str, int]] = []

    for slug, default_name in CANDIDATES.items():
        if slug in existing:
            continue
        ok, count, name = probe(slug)
        if ok and count >= 0:
            display = name if isinstance(name, str) and name != slug else default_name
            new_valid.append((slug, display, count))
            print(f'    "{slug}": "{display}",  # {count}')

    new_valid.sort(key=lambda item: (-item[2], item[1]))
    print(f"\nNew valid boards not in config: {len(new_valid)}")


if __name__ == "__main__":
    main()
